cakehouse/urls.py
from pasteleria.models import Ciudad
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from cakehouse import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'ciudades', views.CiudadViewSet)
router.register(r'comunas', views.ComunaViewSet)
router.register(r'productos', views.ProductoViewSet)
router.register(r'clientes', views.ClienteViewSet)

urlpatterns = [
    path('pasteleria/', include('pasteleria.urls')),
    path('admin/', admin.site.urls),

    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

pasteleria/urls.py
from django.urls import path

from . import views
app_name = 'pasteleria'
urlpatterns = [
    
    path('', views.iniciar_sesion, name='iniciar_sesion'),
    path('autenticar_usuario', views.autenticar_usuario, name='autenticar_usuario'),
    path('cerrar_sesion', views.cerrar_sesion, name='cerrar_sesion'),

    path('agregar_cliente', views.agregar_cliente, name='agregar_cliente'),
    path('registrar_datos', views.registrar_datos, name='registrar_datos'),
    path('registro_clave', views.registro_clave, name='registro_clave'),

    path('menu', views.menu, name='menu'),
    path('menu_denegado', views.menu_denegado, name='menu_denegado'),
    path('<int:producto_id>', views.producto, name='producto'),
    path('<int:producto_id>/pago/', views.pago, name='pago'),
    path('<int:producto_id>/ingresar_pago/', views.ingresar_pago, name='ingresar_pago'),
    path('<int:producto_id>/pago_denegado/', views.pago_denegado, name='pago_denegado'),
   
]

pasteleria/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext as _

class Comuna(models.Model):
    nombre_comuna = models.CharField(max_length=200)
    fecha_comuna = models.DateTimeField('date published')
    def __str__(self):
        return self.nombre_comuna

    def was_published_recently(self):
        return self.pub_fecha >= timezone.now() - datetime.timedelta(days=1)

class Ciudad(models.Model):
    nombre_ciudad = models.CharField(max_length=200)
    fecha_ciudad = models.DateTimeField('date published')
    def __str__(self):
        return self.nombre_ciudad

    def was_published_recently(self):
        return self.pub_fecha >= timezone.now() - datetime.timedelta(days=1)


class Cliente(models.Model):
    run_cliente = models.CharField(max_length=10)
    nombre = models.CharField(max_length=200)
    ap_paterno = models.CharField(max_length=200)
    ap_materno = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    celular = models.CharField(max_length=12)
    direccion = models.CharField(max_length=200)
    numeracion = models.IntegerField(default=0)
    comuna = models.ForeignKey(Comuna, on_delete=models.CASCADE)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE)
    password = models.CharField(max_length=12)
    fecha_cliente = models.DateTimeField('date published')
   
    def __str__(self):
        return self.run_cliente

    def was_published_recently(self):
        return self.pub_fecha >= timezone.now() - datetime.timedelta(days=1)

    class Meta:
        permissions = (
            ('comprador',_('Es comprador' )),
        )



class Producto(models.Model):
    nombre_producto = models.CharField(max_length=200)
    cantidad = models.IntegerField(default=0)
    precio = models.IntegerField(default=0)
    descripcion = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre_producto

class Pago(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    run_cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    nombre_cliente = models.CharField(max_length=200)
    ap_paterno_cliente = models.CharField(max_length=200)
    ap_materno_cliente = models.CharField(max_length=200)
    email_cliente = models.CharField(max_length=200)
    celular_cliente = models.CharField(max_length=12)
    direccion_cliente = models.CharField(max_length=200)
    numeracion_clietne = models.IntegerField(default=0)
    numero_tarjeta = models.IntegerField(default=0)
    mes_expiracion = models.IntegerField(default=0)
    anno_exiparacion = models.IntegerField(default=0)
    cvv = models.IntegerField(default=0)
    

    def __str__(self):
        return'{} - {}'.format(self.run_cliente,self.producto)

pasteleria/views.py
from datetime import time
from django import http
from django.shortcuts import render
from django.http import HttpResponse, response, HttpResponseRedirect
from pasteleria.models import Ciudad, Cliente, Comuna, Producto, Pago
from django.contrib.auth.models import Permission, User
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout


#MENU PRINCIPAL
def menu(request):
    if request.user.is_authenticated:
        listado_producto = Producto.objects.all()
        context = {'listado_producto':listado_producto,'sesion':'Cerrar sesión'}
        return render(request,'pasteleria/menu.html',context)
    else:
        listado_producto = Producto.objects.all()
        context = {'listado_producto':listado_producto}
        return render(request,'pasteleria/menu.html',context)

def menu_denegado(request):
    logout(request)
    listado_producto = Producto.objects.all()
    context = {'listado_producto':listado_producto}
    return render(request,'pasteleria/menu.html',context)


#AGRERGAR CLIENTE
def agregar_cliente(request):
    listado_comuna = Comuna.objects.all()
    listado_ciudad = Ciudad.objects.all()
    context = {'comunas':listado_comuna,'ciudades':listado_ciudad}
    return render(request,'pasteleria/agregar_cliente.html',context)

#REGISTRAR DATOS DEL CLIENTE
def registrar_datos(request):
    listado_comuna = Comuna.objects.all()
    listado_ciudad = Ciudad.objects.all()
    listado_cliente = Cliente.objects.all()
    estado = True

    if request.POST['run'].strip() != "":
        run = request.POST['run'].strip()
    else:
         return render(request, 'pasteleria/agregar_cliente.html', {
            'error_message': "No pueden haber campos vacios",
            'comunas':listado_comuna,
            'ciudades':listado_ciudad})    
    
    if request.POST['nombre'].strip() != "":
        nombre = request.POST['nombre'].strip()
    else:
        return render(request, 'pasteleria/agregar_cliente.html', {
            'error_message': "No pueden haber campos vacios",
            'comunas':listado_comuna,
            'ciudades':listado_ciudad})   

    if request.POST['paterno'].strip() != "":
        paterno = request.POST['paterno'].strip()
    else:
        return render(request, 'pasteleria/agregar_cliente.html', {
            'error_message': "No pueden haber campos vacios",
            'comunas':listado_comuna,
            'ciudades':listado_ciudad})   

    if request.POST['materno'].strip() != "":
        materno = request.POST['materno'].strip()
    else:
        return render(request, 'pasteleria/agregar_cliente.html', {
            'error_message': "No pueden haber campos vacios",
            'comunas':listado_comuna,
            'ciudades':listado_ciudad})   
    
    if request.POST['email'].strip() != "":
        email = request.POST['email'].strip()
    else:
        return render(request, 'pasteleria/agregar_cliente.html', {
            'error_message': "No pueden haber campos vacios",
            'comunas':listado_comuna,
            'ciudades':listado_ciudad})   

    if request.POST['celular'].strip() != "":
        celular = request.POST['celular'].strip()
    else:
        return render(request, 'pasteleria/agregar_cliente.html', {
            'error_message': "No pueden haber campos vacios",
            'comunas':listado_comuna,
            'ciudades':listado_ciudad})   

    if request.POST['direccion'].strip() != "":
        direccion = request.POST['direccion'].strip()
    else:
        return render(request, 'pasteleria/agregar_cliente.html', {
            'error_message': "No pueden haber campos vacios",
            'comunas':listado_comuna,
            'ciudades':listado_ciudad})           
    
    if request.POST['numeracion'].strip() != "":
        num = request.POST['numeracion'].strip()
    else:
        return render(request, 'pasteleria/agregar_cliente.html', {
            'error_message': "No pueden haber campos vacios",
            'comunas':listado_comuna,
            'ciudades':listado_ciudad})    
    
    if request.POST['ciudad'] != "":
        id_ciudad = request.POST['ciudad']
        if request.POST['comuna'] != "":
            id_comuna = request.POST['comuna']
        else:
            return render(request, 'pasteleria/agregar_cliente.html', {
            'error_message': "No pueden haber campos vacios",
            'comunas':listado_comuna,
            'ciudades':listado_ciudad})   
    else:
        return render(request, 'pasteleria/agregar_cliente.html', {
            'error_message': "No pueden haber campos vacios",
            'comunas':listado_comuna,
            'ciudades':listado_ciudad}) 

    ciudad = Ciudad.objects.get(pk = request.POST['ciudad'])
    comuna = Comuna.objects.get(pk = request.POST['comuna'])
    
    for c in listado_cliente:
        if run == c.run_cliente:
            estado = False   
            return render(request, 'pasteleria/agregar_cliente.html', {
            'error_message': "Cliente ya ingresado",
            'comunas':listado_comuna,
            'ciudades':listado_ciudad})   
    if estado == True:
        carrito = {'run':run,'nombre':nombre,'ap_paterno':paterno,'ap_materno':materno,'email':email,'celular':celular,'direccion':direccion,'numeracion':num,'comuna':comuna, 'ciudad':ciudad,'id_ciudad':id_ciudad,'id_comuna':id_comuna}
        return render(request,'pasteleria/registro_clave.html',carrito)


#Registro Contraseña
def registro_clave(request):
    run = request.POST['run']
    nombre = request.POST['nombre']
    paterno = request.POST['paterno']
    materno = request.POST['materno']
    email = request.POST['email']
    celular = request.POST['celular']
    direccion = request.POST['direccion']
    num = request.POST['numeracion']
    id_ciudad = request.POST['ciudad']
    id_comuna = request.POST['comuna']
    ciudad = Ciudad.objects.get(pk = request.POST['ciudad'])
    comuna = Comuna.objects.get(pk = request.POST['comuna'])
    context = {'error':"Contraseña incorrecta, debe tener minimo 6 caracteres y maximo 12.",'error_password':"Ambas contraseñas deben ser iguales.",'run':run,'nombre':nombre,'ap_paterno':paterno,'ap_materno':materno,'email':email,'celular':celular,'direccion':direccion,'numeracion':num,'comuna':comuna, 'ciudad':ciudad,'id_ciudad':id_ciudad,'id_comuna':id_comuna}

    if request.POST['password'].strip() != "":
        password1 = request.POST['password']
        password2 = request.POST['password2']
    else:
        return render(request, 'pasteleria/registro_clave.html', context) 

    caracters_pass = len(password1)

    ciu = Ciudad.objects.get(id = id_ciudad)
    com = Comuna.objects.get(id = id_comuna)
    fecha_hora = timezone.now()

    cliente = Cliente(run_cliente = run, nombre = nombre, ap_paterno = paterno, ap_materno = materno, 
                    email = email, celular = celular, direccion = direccion, numeracion = num, password = password1 ,fecha_cliente = fecha_hora)
    cliente.comuna = com
    cliente.ciudad = ciu

    if caracters_pass <= 12:
        if caracters_pass >= 6:    
            if password1 != password2:
                return render(request, 'pasteleria/registro_clave.html',context) 
            else:
                cliente.save()
                permiso1 = Permission.objects.get(name='Es comprador')
                permiso2 = Permission.objects.get(name='Can view producto')
                user = User.objects.create_user(run,email,password1)
                user.first_name = nombre
                user.last_name = paterno
                user.user_permissions.add(permiso1,permiso2)
                user.is_staff = True
                user.save()
                return HttpResponseRedirect(reverse('pasteleria:iniciar_sesion'))
        else:
            cliente.save()
            permiso1 = Permission.objects.get(name='Es comprador')
            permiso2 = Permission.objects.get(name='Can view producto')   
            user = User.objects.create_user(run,email,password1)
            user.first_name = nombre
            user.last_name = paterno
            user.user_permissions.add(permiso1,permiso2)
            user.is_staff = True
            user.save()
            return HttpResponseRedirect(reverse('pasteleria:iniciar_sesion'))
    else:
        cliente.save()
        permiso1 = Permission.objects.get(name='Es comprador')
        permiso2 = Permission.objects.get(name='Can view producto')
        user = User.objects.create_user(run,email,password1)
        user.first_name = nombre
        user.last_name = paterno
        user.user_permissions.add(permiso1,permiso2)
        user.is_staff = True
        user.save()
        return HttpResponseRedirect(reverse('pasteleria:iniciar_sesion'))

#Iniciar Sesion
def iniciar_sesion (request):
    logout(request)
    return render(request,'pasteleria/iniciar_sesion.html')

#AUTENTICAR USUARIO
def autenticar_usuario (request):
    usuario = request.POST['rut']
    clave= request.POST['password']

    user = authenticate(request, username=usuario, password=clave)

    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('pasteleria:menu'))
    else:
        return render(request, 'pasteleria/iniciar_sesion.html', {
            'error_message': "Rut o Contraseña incorrectos"}) 
#CERRAR SESION
def cerrar_sesion(request):
    logout(request)
    return HttpResponseRedirect(reverse('pasteleria:iniciar_sesion'))

#PRODUCTO
def producto(request,producto_id):
    if request.user.is_authenticated:
        p = Producto.objects.get(id=producto_id)
        context = {'producto':p,'sesion':'Cerrar sesión'}
        return render(request,'pasteleria/producto.html',context)
    else:
        p = Producto.objects.get(id=producto_id)
        context = {'producto':p,'mensaje_prod':'Debe iniciar sesión o registrarse para proceder con la compra.'}

pasteleria/templates/pasteleria/iniciar_sesion.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'pasteleria/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'pasteleria/css/style_login.css' %}">

    <title>Cake House Registrar Usuario</title>
    <link rel="icon" type="image/gif" href="{% static 'pasteleria/img/logo.png' %}">

</head>

<body>
    <header>
        <div class="m-t-menu container-fluid">
            <div class="row">
            <div class="col-sm-1">
                <img src="{% static 'pasteleria/img/logo.png' %}" alt="Logo cake house" width="60">
            </div>
            <div class="menu col-sm-1">
                <a class="letra-menu" href="{% url 'pasteleria:menu_denegado' %}">Menú</a>
            </div>
            <div class="menu col-sm-2">
                <a class="letra-menu" href="#">Login <img class="img-r" src="{% static 'pasteleria/img/man-user.png' %}" alt=""></a>
            </div>
            <div class="menu col-sm-2">
                <a class="letra-menu"  href="http://localhost:8000/api/">Api-Cakehouse <img class="img-c" src="{% static 'pasteleria/img/carrito.png' %}" alt=""></a>
            </div>
            <div class="menu col-sm-2">
                <a class="letra-menu" href="#">Contáctenos <img class="img-con" src="{% static 'pasteleria/img/contacto.png' %}" alt=""></a>
            </div>
            <h5 class=" menu card-title col-sm-2" id="dolar" class="card-text" style="float: right; "></h5>
            <h5 class=" menu card-title col-sm-2" id="euro" class="card-text" style="float: right; "></h5>
            </div>
        </div>
    </header>
    
    <div class="container">
        <div class="row justify-content-center ">
            <div class="col-md-6 col-sm-8 col-xl-4 col-lg-5 formulario">
                <form id="formulario" name="formulario" action="{% url 'pasteleria:autenticar_usuario' %}" name="formulario" method="POST"
                    onsubmit="return  validarForm();">
                    {% csrf_token %}
                    <div class="form-group text-center pt-3">
                        <h1 class="text-black">INICIAR SESIÓN</h1>
                    </div>
                    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                    <div class="form-group mx-sm-4 pt-3">
                        <label for="rut">Run del usario</label>
                        <input type="text" class="form-control" id="rut" name="rut" placeholder="Ej: 00000000-0"
                            oninput="validarRut(this);">
                        <div id="alert-rut" class="alertfa-check-circle alert-light mensaje_alerta" name="alert-rut"
                            role="alert">
                            Debe Ingresar un RUT Valido.
                        </div>
                    </div>
                    <div class="form-group mx-sm-4 pb-3">
                        <label for="password">Ingrese su Contraseña</label>
                        <input type="password" name="password" id="password" class="form-control"
                            placeholder="Contraseña" oninput="validarClave()">
                        <div id="alert-pass1" class="alertfa-check-circle alert-light mensaje_alerta" name="alert-rut"
                            role="alert">
                            Ingrese Contraseña valida que contenga de 6 a 12 caracteres.
                        </div>
                        <br>
                        <input type="checkbox" onclick="myFunction(password)"> Mostrar Contraseña
                    </div>
                    <div class="form-group mx-sm-4 pb-2">
                        <input type="submit" class="ingresar btn btn-outline-secondary btn-lg btn-block btn-estilos"
                            id="btnvalida" value="INGRESAR">
                    </div>
                    <div class="form-group mx-sm-4 text-right">
                        <span class=""><a href="#" class="olvide">Olvidé mi contraseña?</a></span>

                    </div>
                    <div class="form-group text-center">
                        <button class="btn btn-outline-secondary btn-lg btn-block btn-estilos">
                            <a class="olvide1" href="{% url 'pasteleria:agregar_cliente' %}">REGISTRARSE</a>
                        </button>
                    </div>
                    <div class="form-group text-center">
                        <button class="btn btn-outline-secondary btn-lg btn-block btn-estilos">
                            <a class="olvide1" href="{% url 'pasteleria:menu_denegado' %}">INGRESAR COMO INVITADO</a>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    

    <footer class="page-footer font-small">
        <div class="container">
        <ul class="list-unstyled list-inline text-right text-center">
            <img id="logo-footer" src="{% static 'pasteleria/img/logo.png' %}" alt="icon logo">
            <div class="footer-copyright text-center">
            <a id="letra" href="#"><p>© 2021 Copyright: Pasteleria Cake House</p></a>
            </div>
            <li class="list-inline-item">
            <a class="btn-floating btn-fb col-sm-1">
                <p><img class="img-face" src="{% static 'pasteleria/img/incon_face.png' %}" alt="icon facebook"></p>
            </a>
            </li>
            <li class="list-inline-item">
            <a class="btn-floating btn-tw mx-1">
                <p><img class="img-twitter" src="{% static 'pasteleria/img/icon_twitter.png' %}" alt="icon twitter"></p>
            </a>
            </li>
            <li class="list-inline-item">
            <a class="btn-floating btn-gplus mx-1">
                <p><img class="img-wha" src="{% static 'pasteleria/img/icon_wha.png' %}" alt="icon whatsapp"></p>
            </a>
            </li>
            <li class="list-inline-item">
            <a class="btn-floating btn-li mx-1">
                <p><img class="img-ig" src="{% static 'pasteleria/img/icon_ig.png' %}" alt="icon instagram"></p>
            </a>
            </li>
        </ul>
        </div>
    </footer>
    
    <script src="{% static 'pasteleria/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'pasteleria/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'pasteleria/js/login.js' %}"></script>

</body>
</html

pasteleria/templates/pasteleria/pago_denegado.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'pasteleria/css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'pasteleria/css/estilospago.css' %}">
  <title>Cake House Menú</title>
  <link rel="icon" type="image/gif" href="{% static 'pasteleria/img/logo.png' %}">
</head>

<body>
  <!-- Menu superior -->
  <header>
    <div class="m-t-menu container-fluid">
      <div class="row">
        <div class="col-sm-1">
          <img src="{% static 'pasteleria/img/logo.png' %}" alt="Logo cake house" width="60">
        </div>
        <div class="menu col-sm-1">
          <a class="letra-menu" href="{% url 'pasteleria:menu' %}">Menú</a>
        </div>
        <div class="menu col-sm-2">
          <a class="letra-menu" href="{% url 'pasteleria:cerrar_sesion' %}">Cerrar sesión
              </a> <img class="img-r" src="{% static 'pasteleria/img/man-user.png'%}" alt=""></a>
        </div>
        <div class="menu col-sm-2">
            <a class="letra-menu" href="http://localhost:8000/api/">Api-Cakehouse <img class="img-c"
                src="{% static 'pasteleria/img/carrito.png'%}" alt=""></a>
        </div>
        <div class="menu col-sm-2">
          <a class="letra-menu" href="#">Contáctenos <img class="img-con" src="{% static 'pasteleria/img/contacto.png' %}" alt=""></a>
        </div>
        <h5 class=" menu card-title col-sm-2" id="dolar" class="card-text" style="float: right; "></h5>
        <h5 class=" menu card-title col-sm-2" id="euro" class="card-text" style="float: right; "></h5>
      </div>
    </div>
  </header>
  {%if producto %}
  <!-- Titulo de Pastel -->
  <div id="titulo" class="container-fluid">
    <h1>Proceso de Pago</h1>
  </div>

  <div class="alert alert-secondary container" role="alert">
    <p><img src="{% static 'pasteleria/img/danger-sing.png' %}" alt="danger.png" width="20"><b> Por el estado de emergencia actual de nuestro
        país, los pedidos solo se entregaran dentro de la Region Metropolitana. ¡Muchas Gracias!</b></p>
  </div>

  <!-- Detalle Pastel -->
  <main>
    <div id="producto" class="card mb-3 container">
      <div class="row no-gutters">
        <div class="col-md-4">
          {% if producto.id == 1%}
          <img id="imagen" src="{% static 'pasteleria/img/Pastel_cafe2.jpeg' %}" class="card-img" alt="Pastel chocolate">
          {% endif %}
          {% if producto.id == 2%}
          <img id="imagen" src="{% static 'pasteleria/img/pastel_crema.jpeg' %}" class="card-img" alt="Pastel chocolate">
          {% endif %}
          {% if producto.id == 3%}
          <img id="imagen" src="{% static 'pasteleria/img/pastel_frutilla.jpeg' %}" class="card-img" alt="Pastel chocolate">
          {% endif %}
          <h4 id="valor" class="text-muted">{{producto.nombre_producto}}</h4>
          <h4 id="valor" class="text-muted">Valor: ${{producto.precio}}/CLP</h4>
        </div>
        <div class="col-md-8">
          <form action="{% url 'pasteleria:agregar_cliente' %}" id="formulario" name="formulario" method="post">
            {% csrf_token %}
            {% if mensaje %}
            <div class="alert alert-danger rechazo" role="alert">
                <h4 class="alert-heading">Insuficientes Permisos</h4>
                <p>{{mensaje}}</p>
                <hr>
                <p class="mb-0">Para más informacion contactenos a: cakehouse@gmail.com</p>
            </div>
            {% endif %}
            <div class="form-row">
              <div class="form-group col-sm-6">
                <input type="hidden" name="cantidad" value="{{cantidad}}" >
                <input type="submit" value="Registrarme" class="btn" onclick="return validar()">
              </div>
              <div class="form-group col-sm-6">
                <a href="{% url 'pasteleria:producto' producto.id %}" value="Cancelar" class="btn">Cancelar</a>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
  {%endif%}
  <!-- Footer -->
  <footer class="page-footer font-small">
    <div class="container-fluid">
        <ul class="list-unstyled list-inline text-right text-center">

            <a href=""><img id="logo-footer" src="{% static 'pasteleria/img/logo.png'%}" alt="icon logo"></a>
            <div class="footer-copyright text-center">
                <a id="letra" href="#">
                    <p>© 2021 Copyright: Pasteleria Cake House</p>
                </a>
            </div>
            <li class="list-inline-item">
                <a class="btn-floating btn-fb col-sm-1">
                    <p><img class="img-face" src="{% static 'pasteleria/img/incon_face.png'%}" alt="icon facebook">
                    </p>
                </a>
            </li>
            <li class="list-inline-item ">
                <a class="btn-floating btn-tw mx-1">
                    <p><img class="img-twitter" src="{% static 'pasteleria/img/icon_twitter.png'%}"
                            alt="icon twitter"></p>
                </a>
            </li>
            <li class="list-inline-item ">
                <a class="btn-floating btn-gplus mx-1">
                    <p><img class="img-wha" src="{% static 'pasteleria/img/icon_wha.png'%}" alt="icon whatsapp"></p>
                </a>
            </li>
            <li class="list-inline-item ">
                <a class="btn-floating btn-li mx-1">
                    <p><img class="img-ig" src="{% static 'pasteleria/img/icon_ig.png'%}" alt="icon instagram"></p>
                </a>
            </li>
        </ul>
    </div>
</footer>
  <script src="{% static 'pasteleria/js/jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'pasteleria/js/menu.js' %}"></script>
  <script src="{% static 'pasteleria/js/pago.js' %}"></script>
  <script src="{% static 'pasteleria/js/bootstrap.min.js' %}"></script>
</body>

</html